name: nginx
services:
  nginx:
    image: nginx:1.27.4-alpine-slim
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
    restart: unless-stopped